[project]
name = "autotest"
version = "0.1.0"
description = "AITC - 自动化测试工程"
requires-python = ">=3.12"
dependencies = [
    "allure-pytest>=2.13.0",
    "pytest==8.3.4",
    "pytest-html==4.1.1",
    "requests==2.32.3",
    "python-docx==1.1.2",
    "openpyxl==3.1.5",
    "playwright==1.49.1",
    "pytest-playwright==0.6.2",
]
